apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      name: node
    - port: 9422
      targetPort: 9422
      name: metrics
  selector:
    app: {{ .Release.Name }}